<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820135503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_object (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE projet ADD image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE projet DROP image');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA93DA5256D FOREIGN KEY (image_id) REFERENCES media_object (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_50159CA93DA5256D ON projet (image_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE media_object');
        $this->addSql('ALTER TABLE projet DROP CONSTRAINT FK_50159CA93DA5256D');
        $this->addSql('DROP INDEX IDX_50159CA93DA5256D');
        $this->addSql('ALTER TABLE projet ADD image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE projet DROP image_id');
    }
}
