<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804125335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, date_publication TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE projet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, lien VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tag_projet (tag_id INT NOT NULL, projet_id INT NOT NULL, PRIMARY KEY (tag_id, projet_id))');
        $this->addSql('CREATE INDEX IDX_B954D585BAD26311 ON tag_projet (tag_id)');
        $this->addSql('CREATE INDEX IDX_B954D585C18272 ON tag_projet (projet_id)');
        $this->addSql('ALTER TABLE tag_projet ADD CONSTRAINT FK_B954D585BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag_projet ADD CONSTRAINT FK_B954D585C18272 FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tag_projet DROP CONSTRAINT FK_B954D585BAD26311');
        $this->addSql('ALTER TABLE tag_projet DROP CONSTRAINT FK_B954D585C18272');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE projet');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tag_projet');
    }
}
